export const skills = [
  { name: "JavaScript" },
  { name: "TypeScript" },
  { name: "PHP" },
  { name: "React" },
  { name: "Vue" },
  { name: "Angular" },
  { name: "jQuery" },
  { name: "ReactiveX" },
  { name: "Next" },
  { name: "Nuxt" },
  { name: "Laravel" },
  { name: "Webpack" },
  { name: "Slack" },
  { name: "GitHub" },
  { name: "GitLab" },
  { name: "Vercel" },
  { name: "Storybook" },
  { name: "Docker" },
] as const;